//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDU_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Authorized_Persons
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Authorized_Persons()
        {
            this.Cafedras = new HashSet<Cafedra>();
            this.Centers = new HashSet<Center>();
            this.Faculties = new HashSet<Faculty>();
            this.Museums = new HashSet<Museum>();
            this.Prorector_Branchs = new HashSet<Prorector_Branchs>();
        }
    
        public int authorized_person_id { get; set; }
        public string authorized_person_name { get; set; }
        public string authorized_person_surname { get; set; }
        public string authorized_person_father_name { get; set; }
        public string authorized_person_email { get; set; }
        public string authorized_person_password { get; set; }
        public int authorized_person_role_id { get; set; }
        public Nullable<int> authorized_person_degree_id { get; set; }
        public int authorized_person_gender_id { get; set; }
    
        public virtual Degree Degree { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual User_Roles User_Roles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cafedra> Cafedras { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Center> Centers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Faculty> Faculties { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Museum> Museums { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prorector_Branchs> Prorector_Branchs { get; set; }
    }
}
