//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDU_Management.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BDU_ManagementEntities : DbContext
    {
        public BDU_ManagementEntities()
            : base("name=BDU_ManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Authorized_Persons> Authorized_Persons { get; set; }
        public virtual DbSet<Cafedra> Cafedras { get; set; }
        public virtual DbSet<Center> Centers { get; set; }
        public virtual DbSet<Degree> Degrees { get; set; }
        public virtual DbSet<Faculty> Faculties { get; set; }
        public virtual DbSet<Gender> Genders { get; set; }
        public virtual DbSet<Museum> Museums { get; set; }
        public virtual DbSet<Profession_Types> Profession_Types { get; set; }
        public virtual DbSet<Profession> Professions { get; set; }
        public virtual DbSet<Prorector_Branchs> Prorector_Branchs { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<Subject> Subjects { get; set; }
        public virtual DbSet<Teacher> Teachers { get; set; }
        public virtual DbSet<Teachers_Subjects_Pivot> Teachers_Subjects_Pivot { get; set; }
        public virtual DbSet<User_Roles> User_Roles { get; set; }
    }
}
