//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDU_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prorector_Branchs
    {
        public int prorector_branch_id { get; set; }
        public string prorector_branch_name { get; set; }
        public int prorector_branch_prorector_id { get; set; }
    
        public virtual Authorized_Persons Authorized_Persons { get; set; }
    }
}
