//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDU_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int student_id { get; set; }
        public string student_name { get; set; }
        public string student_surname { get; set; }
        public string student_father_name { get; set; }
        public string student_email { get; set; }
        public string student_password { get; set; }
        public int student_gender_id { get; set; }
        public int student_profession_id { get; set; }
    
        public virtual Gender Gender { get; set; }
        public virtual Profession Profession { get; set; }
    }
}
